site_name: Framework3
repo_url: https://github.com/manucouto1/framework3
repo_name: manucouto1/framework3
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - toc.follow
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  logo: icons/f3_white.png
  favicon: icons/f3_white.png
  code:
    highlight_theme: monokai
  # features:
  #   - navigation.expand
  icon:
    edit: material/pencil
    view: material/eye
  # toggle:
  #     icon: material/weather-sunny  # Icono para el toggle
  #     name: Toggle theme            # Texto del toggle
nav:
  - Home: index.md
  - Quick Start: quick_start/index.md
  - Installation: installation/index.md
  - Tutorials:
      - index: examples/index.md
      - Datasets Storage: examples/data_ingestion.md
      - F3Pipeline: examples/simple_f3pipeline.md
  #     - First Filter:
  #     - First Pipeline:
  #     - Caching Data:
  #     - Grid Search:
  #     - Anidating Pipelines:
  #     - Feature Extraction:
  - Api:
      - api/index.md
      - Base:
          - Types: api/base/base_types.md
          - Clases: api/base/base_clases.md
          - Pipeline: api/base/base_pipelines.md
          - Factory: api/base/base_factory.md
          - Storage: api/base/base_storage.md
      - Container:
          - Container: api/container/container.md
          - Overload: api/container/overload.md
      - Plugins:
          - Pipelines:
              - Parallel:
                  - Sequential: api/plugins/pipelines/parallel/mono_pipeline.md
                  - MapReduce: api/plugins/pipelines/parallel/hpc_pipeline.md
              - Sequential:
                  - F3pipeline: api/plugins/pipelines/sequential/f3_pipeline.md
              - Grid:
                  - GridSearchPipeline: api/plugins/pipelines/grid/g3_pipeline.md

          - Filters:
              - Classification: api/plugins/filters/classification.md
              - Clustering: api/plugins/filters/clustering.md
              - Regression: api/plugins/filters/regression.md
              - Cache:
                  - Cached: api/plugins/filters/cache.md
              - Transformation: api/plugins/filters/transformation.md
              - Grid Search: api/plugins/filters/grid_search.md

          - Metrics:
              - Classification: api/plugins/metrics/classification.md
              - Clustering: api/plugins/metrics/clustering.md
              - Coherence: api/plugins/metrics/coherence.md
          - Storage:
              - Local: api/plugins/storage/local.md
              - S3: api/plugins/storage/s3.md
      - Full API Reference: api/index.md

  - Best Practices: best_practices.md

extra:
  social:
    - icon: material/github
      link: https://github.com/manuelcouto1

    - icon: material/linkedin
      link: https://linkedin.com/in/manuel-couto-pintos-96a20a130

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: tabs
          class: tabbed-set
          # format: !!python/name:pymdownx.superfences.fence_div_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes

plugins:
  - search
  - mkdocstrings
  - bibtex:
      bib_file: "docs/references.bib"

extra_css:
  - css/styles.css

copyright: Manuel Couto Pintos
