site_name: LabChain
repo_url: https://github.com/manucouto1/LabChain
repo_name: manucouto1/LabChain
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.select
    - content.code.copy
    - toc.follow
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  logo: icons/f3_white.png
  favicon: icons/f3_white.png
  code:
    highlight_theme: monokai
  # features:
  #   - navigation.expand
  icon:
    edit: material/pencil
    view: material/eye
  # toggle:
  #     icon: material/weather-sunny  # Icono para el toggle
  #     name: Toggle theme            # Texto del toggle
nav:
  - Home:
    - Overview: index.md
    - Quick Start: quick_start/index.md
    - Installation: installation/index.md

  - Architecture: architecture/index.md
  - Tutorials:
      - index: examples/index.md
      - Datasets Storage: examples/data_ingestion.md
      - F3Pipeline: examples/simple_f3pipeline.md
      - Working Examples:
        - Data Ingestion: examples/notebooks/data_ingestion.ipynb
        - Basic Usage: examples/notebooks/simple_custom_filter.ipynb
        - Heavy Data: examples/notebooks/caching_heavy_data.ipynb
        - Optuna: examples/notebooks/optuna_optimizer_with_data_splitter_kfold.ipynb
        - Wandb:  examples/notebooks/wandb_optimizer_with_data_splitter_kfold.ipynb
        - Grid: examples/notebooks/grid_search_optimizer_with_data_splitter_kfold.ipynb
      - Real World:
        - Temporal Word Embeddings for Early Detection of Psychological Disorders on Social Media: examples/notebooks/research_deltas.ipynb
  - API:
      - Overview: api/index.md
      - Base:
          - Types: api/base/base_types.md
          - Plugins: api/base/base_plugin.md
          - Pipeline: api/base/base_pipelines.md
          - Filter: api/base/base_filter.md
          - Metric: api/base/base_metric.md
          - Optimizer: api/base/base_optimizer.md
          - Splitter: api/base/base_splitter.md
          - Factory: api/base/base_factory.md
          - Storage: api/base/base_storage.md
      - Container:
          - Container: api/container/container.md
          - Overload: api/container/overload.md
      - Plugins:
          - Pipelines:
              - Parallel:
                  - MonoPipeline: api/plugins/pipelines/parallel/mono_pipeline.md
                  - HPCPipeline: api/plugins/pipelines/parallel/hpc_pipeline.md
              - Sequential:
                  - F3Pipeline: api/plugins/pipelines/sequential/f3_pipeline.md
          - Filters:
              - Classification: api/plugins/filters/classification.md
              - Clustering: api/plugins/filters/clustering.md
              - Regression: api/plugins/filters/regression.md
              - Transformation: api/plugins/filters/transformation.md
              - Text Processing: api/plugins/filters/text_processing.md
              - Cache:
                  - CachedFilter: api/plugins/filters/cache.md
              - Grid Search:
                  - GridSearchCVFilter: api/plugins/filters/grid_search.md
          - Metrics:
              - Classification: api/plugins/metrics/classification.md
              - Clustering: api/plugins/metrics/clustering.md
              - Coherence: api/plugins/metrics/coherence.md
          - Optimizers:
              - SklearnOptimizer: api/plugins/optimizers/sklearn_optimizer.md
              - OptunaOptimizer: api/plugins/optimizers/optuna_optimizer.md
              - WandbOptimizer: api/plugins/optimizers/wandb_optimizer.md
              - GridOptimizer: api/plugins/optimizers/grid_optimizer.md
          - Splitters:
              - KFoldSplitter: api/plugins/splitters/kfold_splitter.md
              - StratifiedKFoldSplitter: api/plugins/splitters/stratified_kfold_splitter.md
          - Storage:
              - Local: api/plugins/storage/local.md
              - S3: api/plugins/storage/s3.md
      - Utilities:
          - PySpark: api/utils/pyspark.md
          - Weights & Biases: api/utils/wandb.md
          - Typeguar Notebooks: api/utils/typeguard.md
          - Sklearn Estimator: api/utils/sklearn.md
          - Utils: api/utils/utils.md

  - Best Practices:
      - Contributing: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md

extra:
  social:
    - icon: material/github
      link: https://github.com/manuelcouto1

    - icon: material/linkedin
      link: https://linkedin.com/in/manuel-couto-pintos-96a20a130

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true


  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: tabs
          class: tabbed-set
        - name: mermaid
          class: mermaid
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - md_in_html
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.caret

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter
  - bibtex:
      bib_file: "docs/references.bib"

extra_css:
  - css/styles.css
  - css/pygments.css

copyright: Manuel Couto Pintos
